const INVALID_REQUEST = "INVALID_REQUEST";
const EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS";
const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
const UNAUTHORIZED = "UNAUTHORIZED";
const FORBIDDEN = "FORBIDDEN";
const ROOM_ALREADY_EXISTS = "ROOM_ALREADY_EXISTS";
const HOTEL_NOT_FOUND = "HOTEL_NOT_FOUND";
const ROOM_NOT_AVAILABLE = "ROOM_NOT_AVAILABLE";
const INVALID_DATES = "INVALID_DATES";
const INVALID_CAPACITY = "INVALID_CAPACITY";
const ROOM_NOT_FOUND = "ROOM_NOT_FOUND";
const ALREADY_CANCELLED = "ALREADY_CANCELLED";
const CANCELLATION_DEADLINE_PASSED = "CANCELLATION_DEADLINE_PASSED";
const BOOKING_NOT_FOUND = "BOOKING_NOT_FOUND";
const ALREADY_REVIEWED = "ALREADY_REVIEWED";
const BOOKING_NOT_ELIGIBLE = "BOOKING_NOT_ELIGIBLE";

const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";

export {
  ALREADY_CANCELLED,
  ALREADY_REVIEWED,
  BOOKING_NOT_ELIGIBLE,
  BOOKING_NOT_FOUND,
  CANCELLATION_DEADLINE_PASSED,
  EMAIL_ALREADY_EXISTS,
  FORBIDDEN,
  HOTEL_NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  INVALID_CAPACITY,
  INVALID_CREDENTIALS,
  INVALID_DATES,
  INVALID_REQUEST,
  ROOM_ALREADY_EXISTS,
  ROOM_NOT_AVAILABLE,
  ROOM_NOT_FOUND,
  UNAUTHORIZED,
};
